### ISSUE TITLE
simulate_is_correct test fails on Linux :(

### ISSUE THREAD

**Issue by slayoo** [vinecopulib/vinecopulib#170] opened 2017-05-09 08:07 UTC
![image](https://cloud.githubusercontent.com/assets/89685/25841117/30e47bda-349f-11e7-8254-9379f39cf75d.png)

**Comment by tnagler** [comment] 2017-05-11 09:58
This should be fixed, right?

**Comment by slayoo** [comment] 2017-05-11 10:05
no, this fails with current dev branch on my local virtual machine

**Comment by tnagler** [comment] 2017-05-11 10:06
hmm... not on mine and not on travis :/

**Comment by slayoo** [comment] 2017-05-11 10:13
I'll try to debug it

**Comment by slayoo** [comment] 2017-05-11 10:24
```c++
 82     TEST_F(VinecopTest, simulate_is_correct) {
 83
 84         auto pair_copulas = Vinecop::make_pair_copula_store(7);
 85         auto par = Eigen::VectorXd::Constant(1, 3.0);
 86         for (auto& tree : pair_copulas) {
 87             for (auto& pc : tree) {
 88                 pc = Bicop(BicopFamily::clayton, 270, par);
 89             }
 90         }
 91         Vinecop vinecop(pair_copulas, model_matrix);
 92
 93         vinecop.simulate(10);  // only check if it works
 94         // check the underlying transformation from independent samples
 95 std::cerr << u << std::endl;
 96 std::cerr << std::endl;
 97 std::cerr << sim << std::endl;
 98         ASSERT_TRUE(vinecop.inverse_rosenblatt(u).isApprox(sim, 1e-4));
 99     }
```

Here's the output
https://gist.github.com/slayoo/8754d181fbcb2b88e6ff55210b77be5d

**Comment by tnagler** [comment] 2017-05-11 12:06
Could you print `vinecop.inverse_rosenblatt(u)` as well (first couple of rows are sufficient)?

**Comment by slayoo** [comment] 2017-05-11 12:11
https://gist.github.com/slayoo/54cc1534b4af57e7aee4b5d6d25a8d00
third block contains vinecop.inverse_rosenblatt(u)

**Comment by tnagler** [comment] 2017-05-12 15:37
Can't see any obvious pattern. Could you check if VineCopula is on a reasonably recent version on your virtual machine (at least 2.0)?

**Comment by slayoo** [comment] 2017-05-15 07:21
```
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 15.04

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] VineCopula_2.0.6

loaded via a namespace (and not attached):
 [1] ADGofTest_0.3     codetools_0.2-15  lattice_0.20-34   mvtnorm_1.0-5
 [5] stabledist_0.7-1  pspline_1.0-17    foreach_1.4.3     MASS_7.3-45
 [9] grid_3.3.2        stats4_3.3.2      pcaPP_1.9-61      doParallel_1.0.10
[13] Matrix_1.2-7.1    iterators_1.0.8   copula_0.999-15   network_1.13.0
[17] parallel_3.3.2    numDeriv_2016.8-1 gsl_1.9-10.1
```

**Comment by tnagler** [comment] 2017-05-15 11:20
It's strange that it works on all build systems besides your VM, so it's probably something specific to the VM environment. But I really have no clue what's happening.

**Comment by tvatter** [comment] 2017-06-09 12:25
Has anyone been able to reproduce this bug or should we close?

**Comment by tnagler** [comment] 2017-06-09 12:28
Unfortunately only Sylwester can reproduce it.

**Comment by tvatter** [comment] 2017-08-15 16:26
Since it's not reproducible on either travis or our machines, I'm closing for now.

**Closed by tvatter** 2017-08-15 16:26 UTC
Labels: bug
